#!/usr/bin/env bash
# scripts/sync-principals.sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Sync AuthorizedPrincipals files to target VMs
#
# This is the RBAC enforcement mechanism:
# - Vault signs certs with a "principal" (the resource name)
# - The target VM checks the cert's principal against
#   /etc/ssh/auth_principals/<user>
# - If the principal is listed, access is granted
#
# Usage: ./sync-principals.sh
#
# This reads from principals.conf (generated by Terraform output
# or maintained manually) and pushes to all targets.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRINCIPALS_DIR="${SCRIPT_DIR}/../principals.d"

if [ ! -d "$PRINCIPALS_DIR" ]; then
  echo "ERROR: ${PRINCIPALS_DIR} not found."
  echo "Create it with host-specific principal files."
  echo ""
  echo "Structure:"
  echo "  principals.d/"
  echo "    vm-1.lab.internal/"
  echo "      root       # contains: utility-servers"
  echo "      deploy     # contains: utility-servers"
  echo "    bastion.lab.internal/"
  echo "      deploy     # contains: bastion-ssh"
  exit 1
fi

for HOST_DIR in "${PRINCIPALS_DIR}"/*/; do
  HOST=$(basename "$HOST_DIR")
  echo "=== Syncing principals to ${HOST} ==="

  for PRINCIPAL_FILE in "${HOST_DIR}"*; do
    USER=$(basename "$PRINCIPAL_FILE")
    CONTENT=$(cat "$PRINCIPAL_FILE")

    echo "  [+] ${USER}: ${CONTENT}"

    ssh "root@${HOST}" bash -s <<REMOTE
mkdir -p /etc/ssh/auth_principals
echo '${CONTENT}' > /etc/ssh/auth_principals/${USER}
chmod 644 /etc/ssh/auth_principals/${USER}
REMOTE
  done

  echo "  [OK] ${HOST} principals synced"
done

echo ""
echo "=== ALL PRINCIPALS SYNCED ==="
